### ISSUE TITLE
error UnexpectedWriteType("CAS")) with multiple tokio tasks

### ISSUE THREAD

**Issue by devrandom** [krojew/cdrs-tokio#112]
I am getting error `UnexpectedWriteType("CAS"))` when doing batch inserts from multiple tasks in the same `Session` object.

It fails intermittently on a three node cluster with Cassandra version `[cqlsh 6.0.0 | Cassandra 4.0.5 | CQL spec 3.4.5 | Native protocol v5]`.  It works consistently with a single task.

On a local Cassandra instance in docker, it work consistently with multiple tasks - version 4.0.6.

**Comment by krojew** [comment]
Can you check with protocol v4?

**Comment by devrandom** [comment]
Do you mean downgrade to an old Cassandra?  or is there a way to make it fall back to the older protocol?

**Comment by krojew** [comment]
You can specify the protocol version when building connection configuration: https://docs.rs/cdrs-tokio/7.0.0/cdrs_tokio/cluster/struct.NodeTcpConfigBuilder.html#method.with_version

**Comment by devrandom** [comment]
It happens with V3, V4 and V5.  Less often in the older versions.

**Comment by devrandom** [comment]
Also, wanted to mention that this is an LWT batch.  The code in question is here: https://gitlab.com/lightning-signer/validating-lightning-signer/-/merge_requests/312/diffs#144ee5d06667bb53830287a66cd0bda0b514e40c_0_319 (look for `async fn put` if I push again and invalidate the line locator)

**Comment by devrandom** [comment]
The scylla driver gives me a more detailed error:  `Scylla(QueryError(DbError(WriteTimeout { consistency: Serial(LocalSerial), received: 1, required: 2, write_type: Cas }, "Operation timed out - received only 1 responses.")))'`

So cdrs is probably getting confused by the `write_type` on this error.

Well, I'm confused by this error myself...

**Comment by krojew** [comment]
If you're getting it on a two different drivers, it means a problem in your cluster.

**Comment by devrandom** [comment]
agreed.  however, the cdrs driver does eat part of the error - would be good to fix.

**Comment by krojew** [comment]
Sure, I'll take a look.

**Comment by krojew** [comment]
This turns out to be a braking change and will be included in the next major version.

- Add remaining options from https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v5.spec#L1289
- Remove `Copy` from `WriteType`
- Add `UnknownWriteType(String)` variant
- Add non_exhaustive
