### ISSUE TITLE
Trouble with dropped connections on Session

### ISSUE THREAD

**Issue by braje** [krojew/cdrs-tokio#113]
Hello.  I am not sure if this is a bug or user error.  When I am running my test suite against a database, I have noticed that at least a couple of the tests fairly consistently fail with an error:  "Connection closed while waiting for response".  I have tried to run the tests in single threaded mode, I have tried adding connections to the connection pool, but nothing seems to work.  The number of failures vary, the tests which fail vary, etc.  Since it also happens when running with "--jobs 1", I suspect it is not a threading issue.

At the same time, I see cassandra logs that say things like "Unknown exception in client networking" and "Connection reset by peer".  I am running against a single node locally running cassandra test cluster.

I guess my question is whether this seems to be a bug or whether I am supposed to be handling intermittent connection failures like this in my client code.

**Comment by krojew** [comment]
Connections should be brought up according to reconnection policy, so this shouldn't be a problem. The error message suggests something closed the connection while waiting for a response after sending a request. The "Unknown exception in client networking" error suggests something cluster-side. Do you have any more cluster logs?

**Comment by braje** [comment]
Strangely enough, I am doing runs of the tests now and nothing is showing up in the logs, even though I am getting the same errors.  I am running cassandra from within a container, so I wonder if that is causing me grief. I will get back to you.  Thank you for the information!

**Comment by braje** [comment]
I can't get any more log information, so I will just go ahead and close for now.  Thanks for looking at ti.

**Comment by braje** [comment]
I do not.  Can't get any interesting logs.  May as well close .
