### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by Matansegal** [krojew/cdrs-tokio#123]
I was wondering if there is any way of using paging as described here: https://docs.datastax.com/en/developer/java-driver/4.14/manual/core/paging/ ?
I am trying to have a select query, which returns many rows, combined to about 60Mb. the performance is slow (~0.8 sec). I think this is a paging issue.

```rust
let response = session
        .query_with_params(
            SELECT_CQL,
            StatementParamsBuilder::new()
                .with_values(query_values!(id, month))
                .build(),
        )
        .await?
        .response_body()?
        .into_rows();
```

**Comment by krojew** [comment]
Paging is supported: https://docs.rs/cdrs-tokio/latest/cdrs_tokio/cluster/session/struct.Session.html#method.paged

**Comment by Matansegal** [comment]
Thank you!

When I try to use it like here: https://github.com/krojew/cdrs-tokio/blob/bca96dd0929c11a5c0e6b628bbfd654728d33195/cdrs-tokio/examples/paged_query.rs#L155-L160 I get `{unknown}
no method named 'query_with_params' found for struct 'SessionPager' in the current scope`
it looks like it been added after the release of 7.0.1?

**Comment by Matansegal** [comment]
Sorry I missed that the regular query function is `query_with_params` while the one for pager is `query_with_param` (without the s). Do you think it will be a good thought to make them the same?

I looked at the example here: https://github.com/krojew/cdrs-tokio/blob/d0a7e04fb1ab7df31ec774f27b5b86826b00e445/cdrs-tokio/examples/paged_query.rs#L160-L181
and I wonder if there is a way to iterate through the rows in async way?

I tried:
```rust
loop {
        futures.push(tokio::spawn(query_pager.next()));
        if !query_pager.has_more() {
            break;
        }
    }
```
but could not be done due borrowing.

**Comment by krojew** [comment]
Of course - pager is 100% async. The problem with your loop is that you spawn a task for each `next` call. That''s not how async in Rust should be used - simply call `query_pager.next().await` in your loop.

**Comment by Matansegal** [comment]
But then it will await for each iteration to be done. it is not concurrent in this way

**Comment by krojew** [comment]
No - that's not how async works. Each await point switches to another task to proceed concurrently (at least in most runtimes). You can read more about async here: https://rust-lang.github.io/async-book/

**Comment by Matansegal** [comment]
I have this code:
```rust
loop {
        let now = Instant::now();
        for row in query_pager.next().await? {
              results.push(row);
        }

        println!("inside: {}", now.elapsed().as_millis());
        if !query_pager.has_more() {
            break;
        }
    }
```
which doesn't seem to execute concurrently. the sum of the time in each iteration is the total of the whole loop.

**Comment by krojew** [comment]
It executes concurrently with other tasks run by the async executor. What you seem to want is having a _parallel_ pager, which is not possible, since the pager needs to store current state.

**Comment by Matansegal** [comment]
The performance is very similar to the the one without the pager. Isn't it should be different?

**Comment by krojew** [comment]
That depends on the situation. If the performance is the same, that suggests it's not very dependent on the amount of data, but other factors. Pager will usually not give you better performance in itself - its main goal is to split the data when it gets large enough. You can use the pager in combination with async tasks to process rows concurrently as they come, instead of processing on single data set. That should give you a performance boost.

**Comment by Matansegal** [comment]
I see. Thank you so much it was very helpful!
