### ISSUE TITLE
exec_with_params is returning ErrorType::Unprepared.

### ISSUE THREAD

**Issue by rukai** [krojew/cdrs-tokio#162]
Since 8.1.0 (it was working fine in 8.0.0), exec_with_params is returning `ErrorType::Unprepared` in some circumstances.
This should not occur because it is supposed to be handled here: https://github.com/krojew/cdrs-tokio/blob/e38bcc249386c4c6364e44a46eea2904472b57e4/cdrs-tokio/src/cluster/session.rs#L299

edit:
I think the cause would have to involve the attempted retry also hitting an unprepared query error.
Its possible this is the fault of our proxy but afaik the proxy should send the new prepare to all nodes in the cluster, so the second query failing should not be possible.
But the issue was definitely introduced by something in 8.1.0 ...
I will investigate further.

**Comment by krojew** [comment]
Can you check the logs if the statement is being re-prepared and what the result is?

**Comment by rukai** [comment]
[cdrs_log.txt](https://github.com/krojew/cdrs-tokio/files/11426027/cdrs_log.txt)
From the logs it seems like cdrs considers the connection dead after the first failure so it never retries.
I'm guessing at this line https://github.com/krojew/cdrs-tokio/blob/e38bcc249386c4c6364e44a46eea2904472b57e4/cdrs-tokio/src/cluster/session.rs#L331 it silently ignores a failure returned by send_envelopes (probably that it considers the connection dead)

**Comment by krojew** [comment]
Well, it's complicated. It's partly a bug, partly a feature. This kind of error should not result in closing the connection, which is what happened here. But, if all connections to a node were closed, for any reason, it should be marked as down and the reconnection policy should kick in. This is what happened here. With the new reconnection system, some errors should be handled more gracefully.

**Comment by krojew** [comment]
Can you verify branch https://github.com/krojew/cdrs-tokio/tree/bug-162 solves the problem?

**Comment by rukai** [comment]
Yep, that branch fixes the issue, thanks for your help

**Comment by krojew** [comment]
Released 8.1.1.

**Comment by rukai** [comment]
Thanks!
