### ISSUE TITLE
Release new version of cdrs-tokio and cassandra-protocol

### ISSUE THREAD

**Issue by rukai** [krojew/cdrs-tokio#188]
I would appreciate a new release of these crates, I can make a PR to bump the versions if thats helpful?

* cdrs-tokio needs a breaking release due to the upgrade of tokio-rustls which is exposed in the public API of cdrs-tokio
* cassandra-protocol can be a non-breaking release as I didnt see any breaking changes since the last release.

If we are unable to release cdrs-tokio at this time, then a patch release of just cassandra-protocol would be helpful.

Thanks.

**Comment by krojew** [comment]
cdrs-tokio doesn't need a version bump - TLS changes have been already published and introduced no changes to the API. The only changes since the last version were clippy-related. I will publish cassandra-protocol in a few minutes.

**Comment by rukai** [comment]
Thanks!
