### ISSUE TITLE
send_frame locks up on sending large frames >0x20000

### ISSUE THREAD

**Issue by a1ph** [krojew/cdrs-tokio#21]
Hi there,

I've switched to using cdrs-tokio from cdrs few days ago and started noticing some app lock ups. That usually happens when a large frame is being sent. Similar to issue fixed in #4 but on a larger threshold. It now happens when sending frames > ~0x20000 bytes.

Sorry, cannot provide a test case. I'll try to track it down.

Cheers,
-alph

**Comment by krojew** [comment]
I can't see anything in tokio related to this, unfortunately. Can you pause the process in the debugger when it's hanging and see what it's doing?

**Comment by a1ph** [comment]
I have a fix. Let me get it approved for upstream and I'll submit a PR.

**Comment by krojew** [comment]
If you can't create a PR, please share a description of the fix, so I can implement it.

**Comment by a1ph** [comment]
No worries, just got an approval. Sending it out...
