### ISSUE TITLE
provide Authenticators with authentication ResponseBody

### ISSUE THREAD

**Issue by JoshRagem** [krojew/cdrs-tokio#25]
for aws keyspaces, the authentication challenge includes a `nonce` key that is required for signing the auth token (when using aws credentials for cassandra/keyspaces access)

I think the most straightforward way to do this is to pass the auth challenge response body into `Authenticator.auth_token()` -- you can see from [the aws sigv4 java plugin](https://github.com/aws/aws-sigv4-auth-cassandra-java-driver-plugin/blob/d83263421831f8e542ae856de7e189dd9c5bca97/src/main/java/software/aws/mcs/auth/SigV4AuthProvider.java#L187-L227) that this is how the datastax driver works for it's auth plugins

**Comment by krojew** [comment]
I've added a new SaslAuthenticator, which should enable you to implement aws workflow. I don't use aws keyspaces, so I cannot test it. Can you take a look at master?

**Comment by krojew** [comment]
@JoshRagem any chance you can test the changes?

**Comment by JoshRagem** [comment]
Yes I will try that tomorrow

**Comment by JoshRagem** [comment]
@krojew i'm having trouble getting awsv4 signing to work, but the sasl authenticator changes _look_ correct, once I succeed with the signing I can give a better report

**Comment by krojew** [comment]
I added explicit data flush when authenticating, in case there are problems with TLS. If you're having problems with not sending all of the data, this might help.

**Comment by krojew** [comment]
@JoshRagem any news?
