### ISSUE TITLE
Add recreation of forgotten prepared statements

### ISSUE THREAD

**Issue by fggarcia** [krojew/cdrs-tokio#3]
is it possible to applied this fix to this crate @krojew  https://github.com/AlexPikalov/cdrs/pull/348

**Comment by krojew** [comment]
Sure, will get on it sometime next week.

**Comment by fggarcia** [comment]
Thanks you so much @krojew .

could you talk to @AlexPikalov to try to unify the two projects into one?

I think it would be a great option.

or reopen your PR over the crds async version

I'm using your version and it perfect to me.

https://github.com/AlexPikalov/cdrs/issues/356
