### ISSUE TITLE
Update chrono and time deps

### ISSUE THREAD

**Issue by krojew** [krojew/cdrs-tokio#36]
https://rustsec.org/advisories/RUSTSEC-2020-0071
https://rustsec.org/advisories/RUSTSEC-2020-0159

**Comment by conorbros** [comment]
Looks like this has been fixed?

**Comment by krojew** [comment]
@conorbros not yet.

**Comment by krojew** [comment]
Seems to be fixed upstream. Waiting for next release: https://github.com/chronotope/chrono/issues/674
