### ISSUE TITLE
Scope of protocol functionality

### ISSUE THREAD

**Issue by rukai** [krojew/cdrs-tokio#40]
It seems this projects fork predates [cassandra-proto](https://github.com/AlexPikalov/cassandra-proto)

I am in need of a cassandra protocol crate that can support response encoding and query decoding for the purposes of implementing a proxy.
Would that be out of scope of cdrs-tokio's protocol functionality?
Would you be interested in pulling cdrs-tokio's protocol functionality into a cassandra-proto like crate? (I am happy to put in the work to make this happen)

I am currently looking at getting cassandra-proto cleaned up and improved at https://github.com/shotover/cassandra-proto
But this crate is fairly active so it would be a shame to duplicate work.
I would be happy to collaborate in any way that makes sense for your project: possibly a subcrate in this repo or possibly another separate repo.

**Comment by krojew** [comment]
It might be a good idea to extract protocol handling from `cdrs-tokio` into a separate crate. If you wish, you can base on this crate, since it contains multiple protocol improvements over the original cdrs protocol handling, as a subcrate.

**Comment by rukai** [comment]
When you say "as a subcrate" do you mean within the cdrs-tokio repo or for me to make a separate repo for it?

**Comment by krojew** [comment]
I think it's better to keep everything under the same repository - it's easier to work with and update dependencies.

**Comment by rukai** [comment]
Ok sounds good to me!
I'll have some PRs for that soon.

**Comment by krojew** [comment]
Great, thanks!

**Comment by krojew** [comment]
Although naming will be a bit awkward - if there's no dependency on `tokio`, it should be a generic name, yet `cassandra-proto` is already taken. Maybe simply `cassandra-protocol`?

**Comment by rukai** [comment]
hahaha I had just set that name moments ago 
![image](https://user-images.githubusercontent.com/5120858/141734440-03a2b775-6a5d-44c9-973a-7c97d9a3ff3a.png)
:+1:
