### ISSUE TITLE
Release 6.0.0-beta.4

### ISSUE THREAD

**Issue by rukai** [krojew/cdrs-tokio#60]
We have now upstreamed all our changes and would appreciate a 6.0.0-beta.4 release.
There is still a lot more cassandra-protocol improvements to be made before a proper 6.0.0 release though.

**Comment by krojew** [comment]
Done!

**Comment by rukai** [comment]
https://crates.io/crates/cassandra-protocol hmmmm, hasnt shown up yet.

**Comment by krojew** [comment]
cargo, for some reason, didn't publish `cassandra-protocol`. It should be there now.

**Comment by krojew** [comment]
Interesting, seems like nothing got published.
