### ISSUE TITLE
&str in NodeTcpConfig

### ISSUE THREAD

**Issue by maurocchi** [krojew/cdrs-tokio#8]
The `NodeTcpConfig` struct holds a `&str` instead of owning a String.
This forbid writing the following trivial code:
```
let nodes: Vec<NodeTcpConfig<'_>> = service_discovery.services("cassandra").iter()
    .map(|srv| {
        let address = format!("{}:{}", srv.host, srv.port);
        NodeTcpConfigBuilder::new(&address, auth.clone()).build()
        // ^ returns a value referencing data owned by the current function
    })
    .collect();
```

A workaround is to collect all the addresses and then create the nodes, but I'm wondering: what are the benefits of putting a string slice into a config struct?

**Comment by krojew** [comment]
This is a part of the old sync cdrs, so not sure what the intention was - most likely the config was supposed to be created and immediately used. I will introduce owned data, but for now, you can first collect a vector of addresses as a workaround, so the string will not expire.
