### ISSUE TITLE
Error: List should not be empty

### ISSUE THREAD

**Issue by a1ph** [krojew/cdrs-tokio#91]
Hi team,

I'd like to raise this question again. It has been asked a while ago https://github.com/AlexPikalov/cdrs/issues/282 but I think it deserves better handling.

The question is basically about allowing container fields like `Vec<T>` in the structs that make use of `TryFromUdt` or `TryFromRow`. Currently, if a table contains an empty list, `try_from_udt` (`try_from_row`) will fail with the error above.

The proposed solution used to be to wrap all the containers in `Option`, but it is quite inconvenient and looks like an overkill.
An empty list is a valid construct and I do not see a point in requiring that wrapping from the application-level logic.

In our fork of the repo, we have a fix, that allows empty collections. I'd like to check if there are any objections to upstream it?

Thanks,
-alph

**Comment by krojew** [comment]
As far as I know, empty collections are represented as NULL on the protocol level. But, it shouldn't be a problem to handle situations where an empty collection is returned anyway and simply map it to an empty container. If you have a fix ready, I'll be happy to merge it.

**Comment by a1ph** [comment]
Right, so basically an empty collection and null are indistinguishable. So If I want to get `None` for an empty collection, I'd declare it as `Option<Vec<T>>`. If I don't want it to be a special case, and my app just needs to see an empty Vec, then I'd like to use just `Vec<T>`, but the latter case does not currently work.

Thanks for your feedback. I'll prepare a PR later this week.

**Comment by krojew** [comment]
Yes, Cassandra treats empty collections and NULL as equivalent, so wrapping collections in an `Option` might be redundant and actually hard to implement correctly.
