### ISSUE TITLE
Protocol v5 tests

### ISSUE THREAD

**Issue by krojew** [krojew/cdrs-tokio#96]
After introducing protocol v5, we need extensive end-to-end tests on a v5 cluster. Ideally, also regressions checks with v4.

Such tests include running all types of queries with and without compression (everything from section 4 of https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v5.spec), listening to events, using high-level Rust-to-UDT (de)serialization, using different authentication methods.

Note: use the latest Cassandra 4.0 and the **master** branch, since the changes are not published yet.

**Comment by krojew** [comment]
@conorbros have you had a chance to check out the latest master?

**Comment by conorbros** [comment]
@krojew I intend on looking into it this week.
